name: Bicep Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate folder names (lowercase alphabets only, except Build, .git, .github)
        run: |
          invalid_folders=$(find . -mindepth 1 -maxdepth 1 -type d ! -iname 'build' ! -iname '.git' ! -iname '.github' -printf '%f\n' | grep -Ev '^[a-z]+$' || true)
          if [ -n "$invalid_folders" ]; then
            echo "Invalid folder names detected (must be only lowercase alphabets):"
            echo "$invalid_folders"
            exit 1
          fi

      - name: Validate Bicep file names (lowercase alphabets and hyphen, @YYYY-MM-DD.bicep)
        run: |
          invalid_files=$(find . -type f -name '*.bicep' ! -path './Build/*' ! -path './.git/*' ! -path './.github/*' | grep -Ev './[a-z-]+@[0-9]{4}-[0-9]{2}-[0-9]{2}\.bicep$' || true)
          if [ -n "$invalid_files" ]; then
            echo "Invalid Bicep file names detected (must match <lowercase and hyphen>@YYYY-MM-DD.bicep):"
            echo "$invalid_files"
            exit 1
          fi

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_ACR }}

      - name: Set up Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: az bicep install

      - name: Build and Publish Bicep files to ACR
        if: github.ref == 'refs/heads/main'
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: |
          # Find all .bicep files outside the Build folder
          find . -type f -name '*.bicep' ! -path './Build/*' | while read bicepfile; do
            # Get folder name (module) and file name
            folder=$(dirname "$bicepfile" | sed 's|^./||')
            filename=$(basename "$bicepfile")
            # Replace @ with : in file name for versioning
            acr_filename=$(echo "$filename" | sed 's/@/:/g')
            # Remove .bicep extension for ACR module name
            modulename="${acr_filename%.bicep}"
            # Construct ACR target path: <acr-name>.azurecr.io/<folder>/<modulename>
            acr_path="$ACR_NAME.azurecr.io/$folder/$modulename"
            echo "Publishing $bicepfile to $acr_path"
            az bicep publish --file "$bicepfile" --target "br:$acr_path"
          done
